# configs/dataset/ai4arctic.yaml
_target_: pangaea.datasets.ai4arctic.AI4ArcticDataset
dataset_name: ai4arctic_rgb
root_path: /media/turtle-ssd/users/skaushik/Cryo-Data/Benchmark/AI4Arctic
img_size: 224
multi_temporal: 0
multi_modal: false
ignore_index: 255
num_classes: 6
classes:
  - open_water
  - new_ice
  - young_ice
  - thin_first_year_ice
  - thick_first_year_ice
  - old_ice
distribution: [0.65, 0.01, 0.025, 0.021, 0.145, 0.132]

bands:
  optical: [B4, B3, B2]

data_mean:
  optical: [-0.16381396, -0.22024433, -0.12]
data_std:
  optical: [0.61435765, 0.37416646, 0.12]
data_min:
  optical: [0.0, 0.0, 0.0]
data_max:
  optical: [-35.0, -35.0, -35.0]