# configs/dataset/glid.yaml

_target_: pangaea.datasets.glid.GLID
dataset_name: GLID
root_path: /media/turtle-ssd/users/skaushik/Cryo-Data/Benchmark/GLID/GLID/
download_url: ""
auto_download: False

# data properties
img_size: 512
multi_temporal: False
multi_modal: False

# labels
ignore_index: -1
num_classes: 2
classes:
  - Background
  - Target

# optional (kept as placeholder)
distribution: [0.5, 0.5]

# IMPORTANT: match encoder expectation (B4,B3,B2) for RGB (R,G,B)
bands:
  optical: [B4, B3, B2]

# computed from tools/glid_stats.py (train split)
data_mean:
  optical: [120.08558725516001, 124.71967935959498, 123.13973035812378]
data_std:
  optical: [74.64604398949137, 74.35002658020812, 76.54707139907019]

# value ranges (your stats indicate uint8-like scale)
data_min:
  optical: [0.0, 0.0, 0.0]
data_max:
  optical: [255.0, 255.0, 255.0]
