_target_: pangaea.datasets.gssd.GSSD

dataset_name: GSSD
root_path: /mnt/lustre/lalit47/cryo/data/GSSD

download_url: null
auto_download: False

img_size: 512
multi_temporal: False
multi_modal: False

ignore_index: -1
num_classes: 2

classes:
  - Background
  - Supraglacial Debris

distribution:
  - 0.8662
  - 0.1338

bands:
  optical:
    - B2
    - B3
    - B4
    - B8
    - B11
    - B12
    - B8A
    - B5
    - B6
    - B7
  
 
data_mean:
  optical:
    - 0.2004
    - 0.2163
    - 0.2235
    - 0.2415
    - 0.1830
    - 0.1761
    - 0.1813
    - 0.4101
    - 0.4689
    - 0.1117
 
data_std:
  optical:
    - 0.1966
    - 0.1941
    - 0.1919       
    - 0.1762
    - 0.1627
    - 0.1567
    - 0.3303
    - 0.2306
    - 0.3337    
    - 0.1794
 

data_min:
  optical:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  

data_max:
  optical:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
