_target_: pangaea.datasets.zone_mapping_sar.ZONE

dataset_name: zone_mapping
root_path: /mnt/lustre/lalit47/cryo/data/zone_mapping

download_url: null
auto_download: False

img_size: 1024
multi_temporal: False
multi_modal: False

ignore_index: -1
num_classes: 4

classes:
  - class 0
  - Class 1
  - class 2
  - class 3

distribution:
  - 0.0829
  - 0.1501
  - 0.5627
  - 0.2043

bands:
  sar:
    - VV
    #- VH
 
data_mean:
  sar:
    - 73.7227
    #- -23.0533
 
data_std:
  sar:
    - 80.7074
    #- 7.5366
 

data_min:
 sar:
    - 0.0000
    #- -58.0635
  

data_max:
  sar:
    - 255.0000
    #- 10.6666
